# Creating Numpy Array

In [1]:
import numpy as np

In [2]:
data = [1, 3, 5, 7]
print(type(data))
a = np.array(data)
print(type(a))

<class 'list'>
<class 'numpy.ndarray'>


### Not only that but also all  <font color='red'>Iterable</font> 
Iterables include all sequence types (such as list, str, and tuple) and some non-sequence types like dict, file objects.

Objects of any classes you define with an \_\_iter\_\_() method or with a \_\_getitem\_\_()

In [3]:
String = 'HI AI Students'
print(type(String))
a = np.array(String)
print(type(a))

<class 'str'>
<class 'numpy.ndarray'>


In [4]:
Tuple = (1,4,6,7)
print(type(Tuple))
a = np.array(Tuple)
print(type(a))

<class 'tuple'>
<class 'numpy.ndarray'>


In [5]:
Dict = dict({1: 'HI', 2: 'AI', 3: 'Students'})
print(type(Dict))
a = np.array(Dict)
print(type(a))

<class 'dict'>
<class 'numpy.ndarray'>


In [6]:
with open('Text.txt','r') as File:
    print(type(File))
    a = np.array(File)
    print(type(a))

<class '_io.TextIOWrapper'>
<class 'numpy.ndarray'>


# Array Attributes in Numpy


In [7]:
ndarray = np.array([1, 3, 5, 7])
print(ndarray)
print(ndarray.ndim)
print(ndarray.shape)
ndarray.shape = (2,2)
print(ndarray)
print(ndarray.ndim)
print(ndarray.shape)

[1 3 5 7]
1
(4,)
[[1 3]
 [5 7]]
2
(2, 2)


In [8]:
ndarray.size

4

In [9]:
ndarray.dtype

dtype('int32')

# Indexing and Slicing


## Indexing

In [10]:
# Examples for 1D.
a = np.arange(12)
print(a)
a[3]

[ 0  1  2  3  4  5  6  7  8  9 10 11]


3

In [11]:
# Examples for 2D.
a = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
a[1]

array([4, 5, 6, 7])

In [12]:
print(a[1,1])
print(a[1][1])

5
5


## Slicing
**Parts of the array based on the index**

[start : end : step]

If step is not specified, it is assumed as 1.

If start is not mentioned, it is considered 0.

If end is not mentioned, it is considered -1.



In [13]:
# Slicing in 1D.
a = np.arange(12)
print(a)
print(a[6:9])
print(a[6:])


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[6 7 8]
[ 6  7  8  9 10 11]


In [14]:
# Slicing in 2D.
a = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
print(a)
print("="*30)
print(a[1:]) # This will give us rows 1 and 2 and all columns.

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 4  5  6  7]
 [ 8  9 10 11]]


In [15]:
# Now we will get, rows 1 and 2 and column 0.
print(a[1:, 0])
print("="*30)
# Now let's get rows 1 and 2 and columns 1 and 2.
print(a[1:, 1:3])
print("="*30)
# Now let's get alternate rows and columns.
print(a[::2, ::2])

[4 8]
[[ 5  6]
 [ 9 10]]
[[ 0  2]
 [ 8 10]]


# Filtering

In [16]:
a = np.arange(1,13)
filter_a = a % 2 == 0 
print(filter_a)

[False  True False  True False  True False  True False  True False  True]


In [17]:
a[filter_a]

array([ 2,  4,  6,  8, 10, 12])

In [18]:
a[a%3 == 0]

array([ 3,  6,  9, 12])

## Filter Using Multiple Conditions

In [19]:
filter_a1 = a > 7
a[filter_a & filter_a1]

array([ 8, 10, 12])

In [20]:
a[( a % 2 == 0 ) & (a > 7)]

array([ 8, 10, 12])

# Arithmetic Operations

In [21]:
a = np.array([1, 2, 3])
b = 3
a+b

array([4, 5, 6])

In [22]:
a*b

array([3, 6, 9])

In [23]:
c = np.array([4, 5, 6])
a+c 

array([5, 7, 9])

In [24]:
a*c

array([ 4, 10, 18])

In [25]:
a1 = np.array([[1,2,3],[4,5,6]])
b = 3
a1+b

array([[4, 5, 6],
       [7, 8, 9]])

In [26]:
a1*b

array([[ 3,  6,  9],
       [12, 15, 18]])

In [27]:
a1+c

array([[ 5,  7,  9],
       [ 8, 10, 12]])

In [28]:
a1*c

array([[ 4, 10, 18],
       [16, 25, 36]])